### ISSUE TITLE
Won't install, needs git

### ISSUE THREAD

**Issue by BHare1985** [naturalatlas/tilestrata-mapnik#1]
Seems git is required.

npm http GET https://registry.npmjs.org/tilestrata-mapnik
npm http 304 https://registry.npmjs.org/tilestrata-mapnik
npm http GET https://registry.npmjs.org/lodash
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.36\
tools\node.exe" "C:\ProgramData\chocolatey\lib\npm.1.4.9\tools\node_modul
es\npm\bin\npm-cli.js" "install" "tilestrata-mapnik" "--save"
npm ERR! cwd C:\Users\Brian\Desktop\nodeMapnik
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.9
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/lodash
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Brian\Desktop\nodeMapnik\npm-debug.log
npm ERR! not ok code 0

**Comment by brianreavis** [comment]
Mind giving 0.2.3 a shot?

**Comment by BHare1985** [comment]
Works without git now (uninstalled git and tried)
