### ISSUE TITLE
Double database calls when using UTFgrid and Tiles

### ISSUE THREAD

**Issue by BHare1985** [naturalatlas/tilestrata-mapnik#2]
Using your sample:

```
var mapnik = require('tilestrata-mapnik');

server.layer('mylayer')
    .route('tile.png').use(mapnik({
            xml: '/path/to/map.xml',
            scale: 1,
            tileSize: 256
        }));
    })
    .route('tile.json').use(mapnik({
        xml: '/path/to/map.xml',
        scale: 1,
        tileSize: 256,
        interactivity: true
    }));
```

This results in 2x the calls to database, doing the same calls both for tiles and for utfgrid. Is there anyway you can detect if it's the same xml to use the same database results for both?

Also the sample code has an error, I had to remove the `})` and `;`

**Comment by brianreavis** [comment]
Thanks for the heads up on the typo (fixed now). As for the double database queries/layout... this is how mapnik is designed at the moment and there's no way around it currently. If that ever changes I'll certainly update the plugin to accommodate – I've been wanting the same thing.
