### ISSUE TITLE
Allow passing an xml string instead of a file

### ISSUE THREAD

**Issue by vjpr** [naturalatlas/tilestrata-mapnik#4]

**Comment by brianreavis** [comment]
I think this would be good idea going forward but it might mean we need to ditch [tilelive-mapnik](https://github.com/mapbox/tilelive-mapnik) under the hood. It does seem there is an undocumented `"xml"` argument it supports [here](https://github.com/mapbox/tilelive-mapnik/blob/master/lib/mapnik_backend.js#L206-L218). That feels like a really bad hack though... `encodeURIComponent` for a mapnik XML (which are often quite large) seems crazy. I'd almost rather re-define `MapnikSource.prototype._loadXML` than do that.

**Comment by BHare1985** [comment]
If loading XML from a string was considered you may look at Grainstore https://github.com/CartoDB/grainstore  (see my fork for a windows compatible one with less requirements) to dynamically create mapnik XML strings on the fly using cartocss. That is how I was able to allow https://github.com/BHare1985/Windwalker to accept dynamic sql and styles based on a request (querystrings, session ids, cookies, etc).

`tilelive.load` will accept an XML string in the xml property of the object passed to it, see here https://github.com/BHare1985/Windwalker/blob/master/lib/render_cache.js#L111

**Comment by apeters** [comment]
This can be accomplished with only just a minor change to the initialize function within index.js

The **original** code:

``` javascript
    function initialize(server, callback) {
        var url = 'mapnik://' + options.xml + '?' + [
            'metatile=' + options.metatile,
            'resolution=' + options.resolution,
            'bufferSize=' + options.bufferSize,
            'tileSize=' + options.tileSize,
            'scale=' + options.scale
        ].join('&');

        new MapnikBackend(url, function(err, result) {
            source = result;
            callback(err);
        });
    }
```

The **new** code:

``` javascript
    function initialize(server, callback) {
        new MapnikBackend(options, function(err, result) {
            source = result;
            callback(err);
        });
    }
```

To use, the **xml property** now refers to a string of mapnik xml, and the **pathname property** refers to the path to an xml file: 

``` javascript
    server.layer('mylayer')
        .route('tile.png').use(mapnik({
            pathname: '/path/to/map.xml file',
            scale: 1,
            tileSize: 256
        })
        .route('tile.json').use(mapnik({
            xml: 'string of mapnik xml',
            scale: 1,
            tileSize: 256,
            interactivity: true
        }));
```

**Comment by brianreavis** [comment]
@apeters Aha, awesome! I hadn't noticed [mapnik_backend.js#L71](https://github.com/mapbox/tilelive-mapnik/blob/master/lib/mapnik_backend.js#L71). The number of hacky tilelive conventions never ceases to amaze. Do you want to open a PR for this change? Getting away from the URI-building would be great

**Comment by brianreavis** [comment]
https://github.com/naturalatlas/tilestrata-mapnik/releases/tag/v0.4.0

**Comment by BHare1985** [comment]
~~Shouldn't this now v1.0.0 according to http://semver.org/ ?~~

~~semver is the adopted/recommended versioning for nodejs packages. Specifically someone may have `"tilestrata-mapnik": "0.x.0"` in their package.json expecting no code-breaking changes.~~

~~Probably not enough adopters yet to really worry about this, but just for future reference.~~

Edit: Nevermind, because this is before 1.0.0 anything goes.

**Comment by davenquinn** [comment]
This seems to be broken in `0.4.1`. I'm getting a "Path must be a string. Received undefined" error when I pass the `xml` option. When I write to a file and pass `pathname` everything works fine.

**Comment by brianreavis** [comment]
@davenquinn Could you open a new issue for this? 

We don't emit that error anywhere, so it might be mapnik related. Could you post the full stack trace? What version of node-mapnik are you using?
